using System;
using System.Diagnostics;

namespace GitLabCmd.Core
{
    public sealed class ResultCommonLogic
    {
        public bool IsFailure { get; }
        public bool IsSuccess => !IsFailure;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly string _error;

        public string Error
        {
            [DebuggerStepThrough]
            get
            {
                if (IsSuccess)
                    throw new InvalidOperationException("There is no error message for success.");

                return _error;
            }
        }

        [DebuggerStepThrough]
        public ResultCommonLogic(bool isFailure, string error)
        {
            if (isFailure)
            {
                if (string.IsNullOrEmpty(error))
                    throw new ArgumentNullException(nameof(error), "There must be error message for failure.");
            }
            else
            {
                if (error != null)
                    throw new ArgumentException("There should be no error message for success.", nameof(error));
            }

            IsFailure = isFailure;
            _error = error;
        }
    }

    public struct Result
    {
        private static readonly Result _okResult = new Result(false, null);

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly ResultCommonLogic _logic;

        public bool IsFailure => _logic.IsFailure;
        public bool IsSuccess => _logic.IsSuccess;
        public string Error => _logic.Error;

        [DebuggerStepThrough]
        private Result(bool isFailure, string error) => _logic = new ResultCommonLogic(isFailure, error);

        [DebuggerStepThrough]
        public static Result Ok() => _okResult;

        [DebuggerStepThrough]
        public static Result Fail(string error) => new Result(true, error);

        [DebuggerStepThrough]
        public static Result<T> Ok<T>(T value) => new Result<T>(false, value, null);

        [DebuggerStepThrough]
        public static Result<T> Fail<T>(string error) => new Result<T>(true, default, error);

        [DebuggerStepThrough]
        public static Result<T> Fail<T>(Result result) => new Result<T>(true, default, result.Error);
    }

    public struct Result<T>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly ResultCommonLogic _logic;

        public bool IsFailure => _logic.IsFailure;
        public bool IsSuccess => _logic.IsSuccess;
        public string Error => _logic.Error;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private readonly T _value;

        public T Value
        {
            [DebuggerStepThrough]
            get
            {
                if (!IsSuccess)
                    throw new InvalidOperationException("There is no value for failure.");

                return _value;
            }
        }

        public Result<V> Map<V>(Func<T, V> mapFunc)
        {
            return IsSuccess ? Result.Ok(mapFunc(Value)) : Result.Fail<V>(Error);
        }

        [DebuggerStepThrough]
        internal Result(bool isFailure, T value, string error)
        {
            if (!isFailure && value == null)
                throw new ArgumentNullException(nameof(value));

            _logic = new ResultCommonLogic(isFailure, error);
            _value = value;
        }

        public static implicit operator Result(Result<T> result) =>
            result.IsSuccess ? Result.Ok() : Result.Fail(result.Error);
    }
}